CREATE OR REPLACE VIEW public.tenants_public AS
SELECT
  id, name, slug, logo_url, address, phone, whatsapp, description, active,
  delivery_mode, niche, is_dropshipping, platform_fee, platform_fee_percent,
  shipping_enabled, shipping_base_fee, shipping_base_radius_km, shipping_per_km_fee,
  shipping_origin_address, shipping_mode, shipping_max_fee, shipping_lalamove_auto,
  shipping_lalamove_margin_percent, shipping_lalamove_apply_cap, delivery_max_radius_km,
  splash_bg_color, brand_primary_color, brand_bg_color, promo_title, promo_text, promo_active,
  store_mode, pickup_enabled, pix_key, pix_key_type, delivery_responsible,
  lalamove_enabled, lalamove_market, lalamove_sandbox,
  printer_enabled, printer_paper_width,
  scheduling_auto_confirm, scheduling_enabled, scheduling_open_days, scheduling_open_time,
  scheduling_close_time, scheduling_slot_minutes, scheduling_capacity,
  quotes_enabled, quotes_intro_text, quotes_feature_enabled,
  fee_mode, fee_split_store_percent, billing_mode, monthly_fee, is_donated,
  auto_dropshipping_enabled, dropshipping_review_mode,
  sound_alert_enabled, sound_alert_loud,
  blocked, blocked_reason, blocked_at,
  demo_payment_enabled, catalog_layout,
  created_at, updated_at,
  mercadopago_token IS NOT NULL AND length(mercadopago_token) > 0 AS has_online_payment,
  dropshipping_submode, dropshipping_freight_mode,
  whatsapp_consultora_phone, whatsapp_store_address,
  whatsapp_store_cep, whatsapp_default_address_source
FROM tenants;